-- Game Engine SDK catalog rows (requires migration 0005).
-- New games use the engine/variation columns; the legacy game each one replaces is disabled here.
-- maxScore = roundCount x the engine's per-answer maximum (30 with default scoring).

INSERT INTO mini_games (key, title, blurb, status, sort_order, config, engine, variation, config_version, score_direction) VALUES
  ('guess_flag', 'Guess the Flag', 'Name the country from its flag. 10 rounds, getting harder as you go.', 'enabled', 20,
   '{"engine": "guess", "variation": "flag", "roundCount": 10, "maxScore": 300, "genre": "trivia", "tag": "TRIVIA"}', 'guess', 'flag', 1, 'higher_is_better'),
  ('guess_indian_state', 'Guess the State', 'Clue by clue — which Indian state is it?', 'enabled', 21,
   '{"engine": "guess", "variation": "indian_state", "roundCount": 10, "maxScore": 300, "genre": "trivia", "tag": "TRIVIA", "content": {"categories": ["india"]}}', 'guess', 'indian_state', 1, 'higher_is_better'),
  ('guess_food', 'Guess the Dish', 'Emoji and clues — name the dish.', 'enabled', 22,
   '{"engine": "guess", "variation": "food", "roundCount": 10, "maxScore": 300, "genre": "trivia", "tag": "FOOD"}', 'guess', 'food', 1, 'higher_is_better'),
  ('guess_landmark', 'Guess the Landmark', 'From the Taj to the Eiffel Tower — name it from clues.', 'enabled', 23,
   '{"engine": "guess", "variation": "landmark", "roundCount": 10, "maxScore": 300, "genre": "trivia", "tag": "TRIVIA"}', 'guess', 'landmark', 1, 'higher_is_better'),
  ('emoji_movie', 'Emoji Movies', 'Bollywood and Hollywood hits, told in emoji.', 'enabled', 24,
   '{"engine": "emoji_guess", "variation": "movie", "roundCount": 10, "maxScore": 300, "genre": "word", "tag": "MOVIES"}', 'emoji_guess', 'movie', 1, 'higher_is_better'),
  ('emoji_bollywood', 'Bollywood in Emoji', 'Can you decode these Bollywood films?', 'enabled', 25,
   '{"engine": "emoji_guess", "variation": "movie", "roundCount": 10, "maxScore": 300, "genre": "word", "tag": "MOVIES", "category": "bollywood"}', 'emoji_guess', 'movie', 1, 'higher_is_better'),
  ('emoji_phrase', 'Emoji Phrases', 'Idioms and sayings hidden in emoji.', 'enabled', 26,
   '{"engine": "emoji_guess", "variation": "phrase", "roundCount": 10, "maxScore": 300, "genre": "word", "tag": "WORD"}', 'emoji_guess', 'phrase', 1, 'higher_is_better'),
  ('emoji_word', 'Emoji Words', 'Two emoji, one word. Decode the compound.', 'enabled', 27,
   '{"engine": "emoji_guess", "variation": "word", "roundCount": 10, "maxScore": 300, "genre": "word", "tag": "WORD"}', 'emoji_guess', 'word', 1, 'higher_is_better'),
  ('odd_words', 'Odd One Out: Words', 'Four words, one impostor. Find it fast.', 'enabled', 28,
   '{"engine": "odd_one_out", "variation": "words", "roundCount": 10, "maxScore": 300, "genre": "puzzle", "tag": "PUZZLE"}', 'odd_one_out', 'words', 1, 'higher_is_better'),
  ('odd_emoji', 'Odd One Out: Emoji', 'Which picture does not belong?', 'enabled', 29,
   '{"engine": "odd_one_out", "variation": "emoji", "roundCount": 10, "maxScore": 300, "genre": "puzzle", "tag": "PUZZLE"}', 'odd_one_out', 'emoji', 1, 'higher_is_better'),
  ('odd_numbers', 'Odd Number Out', 'Spot the number that breaks the pattern.', 'enabled', 30,
   '{"engine": "odd_one_out", "variation": "numbers", "roundCount": 10, "maxScore": 300, "genre": "puzzle", "tag": "PUZZLE"}', 'odd_one_out', 'numbers', 1, 'higher_is_better'),
  ('odd_lookalike', 'Emoji Lookalikes', 'One tile is slightly different. Can you see it?', 'enabled', 31,
   '{"engine": "odd_one_out", "variation": "lookalike", "roundCount": 10, "maxScore": 300, "genre": "puzzle", "tag": "PUZZLE"}', 'odd_one_out', 'lookalike', 1, 'higher_is_better'),
  ('tap_rush', 'Target Rush', 'Three 12-second rounds. Tap the targets before they vanish.', 'enabled', 32,
   '{"engine": "tap", "variation": "rush", "maxScore": 5226, "genre": "arcade", "tag": "ARCADE"}', 'tap', 'rush', 1, 'higher_is_better'),
  ('tap_moles', 'Whack-a-Mole', 'Bop the moles as they pop up. Stars are worth double.', 'enabled', 33,
   '{"engine": "tap", "variation": "moles", "maxScore": 5226, "genre": "arcade", "tag": "ARCADE"}', 'tap', 'moles', 1, 'higher_is_better'),
  ('tap_reaction', 'Reaction Time', 'Wait for green, then tap. Five tries, watch for false cues.', 'enabled', 34,
   '{"engine": "tap", "variation": "reaction", "maxScore": 750, "genre": "arcade", "tag": "ARCADE"}', 'tap', 'reaction', 1, 'higher_is_better'),
  ('word_search', 'Word Search', 'Three themed grids. Drag across the hidden words.', 'enabled', 35,
   '{"engine": "word_search", "variation": "classic", "maxScore": 1284, "genre": "word", "tag": "WORD"}', 'word_search', 'classic', 1, 'higher_is_better'),
  ('word_search_india', 'Desi Word Search', 'Cities, rivers, sweets and spices of India.', 'enabled', 36,
   '{"engine": "word_search", "variation": "classic", "maxScore": 1284, "genre": "word", "tag": "WORD", "category": "india"}', 'word_search', 'classic', 1, 'higher_is_better'),
  ('word_search_blitz', 'Word Search Blitz', 'Five quick grids against the clock.', 'enabled', 37,
   '{"engine": "word_search", "variation": "blitz", "maxScore": 2140, "genre": "word", "tag": "WORD"}', 'word_search', 'blitz', 1, 'higher_is_better'),
  ('word_search_mystery', 'Mystery Words', 'You get the theme and the lengths. Find the words.', 'enabled', 38,
   '{"engine": "word_search", "variation": "mystery", "maxScore": 1284, "genre": "word", "tag": "WORD"}', 'word_search', 'mystery', 1, 'higher_is_better'),
  ('spot_shapes', 'Spot the Difference', 'Two neon pictures, a handful of changes. Find them all.', 'enabled', 39,
   '{"engine": "spot_difference", "variation": "shapes", "maxScore": 690, "genre": "puzzle", "tag": "PUZZLE"}', 'spot_difference', 'shapes', 1, 'higher_is_better'),
  ('spot_city', 'Spot It: Night City', 'Windows, towers and the moon. What changed?', 'enabled', 40,
   '{"engine": "spot_difference", "variation": "city", "maxScore": 690, "genre": "puzzle", "tag": "PUZZLE"}', 'spot_difference', 'city', 1, 'higher_is_better'),
  ('spot_garden', 'Spot It: Garden', 'Flowers, clouds and butterflies with a few sneaky edits.', 'enabled', 41,
   '{"engine": "spot_difference", "variation": "garden", "maxScore": 690, "genre": "puzzle", "tag": "PUZZLE"}', 'spot_difference', 'garden', 1, 'higher_is_better'),
  ('spot_space', 'Spot It: Space', 'Planets, stars and a rocket. Compare carefully.', 'enabled', 42,
   '{"engine": "spot_difference", "variation": "space", "maxScore": 690, "genre": "puzzle", "tag": "PUZZLE"}', 'spot_difference', 'space', 1, 'higher_is_better'),
  ('fact_fake', 'Fact or Fake', 'Swipe right for fact, left for fake. Ten statements, no mercy.', 'enabled', 43,
   '{"engine": "fact_fake", "variation": "mixed", "roundCount": 10, "maxScore": 300, "genre": "trivia", "tag": "TRIVIA"}', 'fact_fake', 'mixed', 1, 'higher_is_better'),
  ('fact_fake_india', 'Fact or Fake: India', 'History, places and culture. Can you tell true from made-up?', 'enabled', 44,
   '{"engine": "fact_fake", "variation": "india", "roundCount": 10, "maxScore": 300, "genre": "trivia", "tag": "TRIVIA"}', 'fact_fake', 'india', 1, 'higher_is_better'),
  ('fact_fake_science', 'Fact or Fake: Science', 'Space, animals and the human body. Myths beware.', 'enabled', 45,
   '{"engine": "fact_fake", "variation": "science", "roundCount": 10, "maxScore": 300, "genre": "trivia", "tag": "TRIVIA"}', 'fact_fake', 'science', 1, 'higher_is_better'),
  ('fact_fake_sports', 'Fact or Fake: Sports', 'Cricket, Olympics and more.', 'enabled', 46,
   '{"engine": "fact_fake", "variation": "sports", "roundCount": 10, "maxScore": 300, "genre": "trivia", "tag": "TRIVIA"}', 'fact_fake', 'sports', 1, 'higher_is_better'),
  ('fact_fake_filmy', 'Fact or Fake: Filmy', 'Movies and music trivia, true or totally made up.', 'enabled', 47,
   '{"engine": "fact_fake", "variation": "entertainment", "roundCount": 10, "maxScore": 300, "genre": "trivia", "tag": "TRIVIA"}', 'fact_fake', 'entertainment', 1, 'higher_is_better'),
  ('this_or_that', 'This or That', 'Pick a side, then see where the crowd stands.', 'enabled', 48,
   '{"engine": "choice", "variation": "this_or_that", "roundCount": 10, "maxScore": 200, "genre": "social", "tag": "SOCIAL"}', 'choice', 'this_or_that', 1, 'higher_is_better'),
  ('food_fight', 'Food Fight', 'Chai or coffee? Biryani or pulao? Choose wisely.', 'enabled', 49,
   '{"engine": "choice", "variation": "food_fight", "roundCount": 10, "maxScore": 200, "genre": "social", "tag": "SOCIAL"}', 'choice', 'food_fight', 1, 'higher_is_better'),
  ('desi_debates', 'Desi Debates', 'The great Indian either-or.', 'enabled', 50,
   '{"engine": "choice", "variation": "desi", "roundCount": 10, "maxScore": 200, "genre": "social", "tag": "SOCIAL"}', 'choice', 'desi', 1, 'higher_is_better'),
  ('read_the_crowd', 'Read the Crowd', 'Guess which side most players picked. The closer the split, the harder it gets.', 'enabled', 51,
   '{"engine": "choice", "variation": "crowd", "roundCount": 10, "maxScore": 300, "genre": "social", "tag": "SOCIAL"}', 'choice', 'crowd', 1, 'higher_is_better'),
  ('tap_dont_tap', 'Green Light, Red Light', 'Tap green, skip red. Then the rules flip. Three lives.', 'enabled', 52,
   '{"engine": "tap_dont_tap", "variation": "flip", "lives": 3, "maxScore": 5384, "genre": "arcade", "tag": "ARCADE"}', 'tap_dont_tap', 'flip', 1, 'higher_is_better'),
  ('fruit_frenzy', 'Fruit Frenzy', 'Tap the fruit, never the junk food. Three lives.', 'enabled', 53,
   '{"engine": "tap_dont_tap", "variation": "fruit", "lives": 3, "maxScore": 4686, "genre": "arcade", "tag": "ARCADE"}', 'tap_dont_tap', 'fruit', 1, 'higher_is_better'),
  ('balloon_pop', 'Balloon Pop', 'Pop the balloons, dodge the bombs. Three lives.', 'enabled', 54,
   '{"engine": "tap_dont_tap", "variation": "balloons", "lives": 3, "maxScore": 4686, "genre": "arcade", "tag": "ARCADE"}', 'tap_dont_tap', 'balloons', 1, 'higher_is_better'),
  ('maze_runner', 'Maze Runner', 'Three mazes, growing bigger. Find the exit fast.', 'enabled', 55,
   '{"engine": "maze", "variation": "classic", "maxScore": 435, "genre": "puzzle", "tag": "PUZZLE"}', 'maze', 'classic', 1, 'higher_is_better'),
  ('maze_gems', 'Gem Hunt', 'Grab every gem to unlock the exit.', 'enabled', 56,
   '{"engine": "maze", "variation": "gems", "maxScore": 585, "genre": "puzzle", "tag": "PUZZLE"}', 'maze', 'gems', 1, 'higher_is_better'),
  ('maze_fog', 'Into the Fog', 'A maze you can only see a few steps of.', 'enabled', 57,
   '{"engine": "maze", "variation": "fog", "maxScore": 435, "genre": "puzzle", "tag": "PUZZLE"}', 'maze', 'fog', 1, 'higher_is_better'),
  ('maze_sprint', 'Maze Sprint', 'Five quick mazes on a short clock.', 'enabled', 58,
   '{"engine": "maze", "variation": "sprint", "maxScore": 725, "genre": "puzzle", "tag": "PUZZLE"}', 'maze', 'sprint', 1, 'higher_is_better'),
  ('connect_dots', 'Connect the Dots', 'Join every pair without crossing. Fill the board for a bonus.', 'enabled', 59,
   '{"engine": "connect_dots", "variation": "classic", "maxScore": 510, "genre": "puzzle", "tag": "PUZZLE"}', 'connect_dots', 'classic', 1, 'higher_is_better'),
  ('connect_blitz', 'Connect Blitz', 'Five small boards, short clock.', 'enabled', 60,
   '{"engine": "connect_dots", "variation": "blitz", "maxScore": 850, "genre": "puzzle", "tag": "PUZZLE"}', 'connect_dots', 'blitz', 1, 'higher_is_better'),
  ('connect_xl', 'Connect XL', 'Two big boards for patient minds.', 'enabled', 61,
   '{"engine": "connect_dots", "variation": "big", "maxScore": 340, "genre": "puzzle", "tag": "PUZZLE"}', 'connect_dots', 'big', 1, 'higher_is_better')
ON CONFLICT (key) DO UPDATE SET
  title = EXCLUDED.title,
  blurb = EXCLUDED.blurb,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  config = EXCLUDED.config,
  engine = EXCLUDED.engine,
  variation = EXCLUDED.variation,
  config_version = EXCLUDED.config_version,
  score_direction = EXCLUDED.score_direction;

-- Retired legacy games: the six with a replacement engine above, then the ten not on the MVP game map.
UPDATE mini_games SET status = 'disabled' WHERE key IN (
  'flag_rush', 'emoji_decode', 'odd_one_out', 'frenzy_tap', 'traffic_light', 'grid_hunt',
  'higher_or_lower', 'memory_sequence', 'timer_stop', 'color_match', 'perfect_circle',
  'bubble_burst', 'lane_dash', 'triple_match', 'word_scramble', 'word_blitz'
);
